FROM nvidia/cuda:11.2.2-devel-ubuntu18.04

USER root
WORKDIR /home
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV LC_ALL "C.UTF-8"
ENV HOME "/home"
ENV PATH "$PATH:/usr/local/cuda/bin"
ENV LD_LIBRARY_PATH "$LD_LIBRARY_PATH:/usr/local/cuda/lib64"

RUN apt-get update && apt-get -y install build-essential gfortran wget
RUN cd /home && wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.gz && tar xvzf openmpi-4.0.3.tar.gz 
RUN cd /home/openmpi-4.0.3 && ./configure --prefix=/home/opt/openmpi && make all && make install

ENV PATH "$PATH:/home/opt/openmpi/bin"
ENV LD_LIBRARY_PATH "$LD_LIBRARY_PATH:/home/opt/openmpi/lib"
ENV OMPI_ALLOW_RUN_AS_ROOT 1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM 1

RUN echo $PATH && echo $LD_LIBRARY_PATH
RUN apt-get -y install git python3.6 python3.6-dev python3-pip python-tk
RUN pip3 install requests h5py==3.1.0 kiwisolver==1.0.1 matplotlib==3.1.3 numpy==1.18.1 scipy==1.4.1 --user

RUN cd /home && git clone https://github.com/anstmichaels/emopt.git && cd emopt && sed -i 's/openblas/fblaslapack=1/g' install.py
RUN cd /home/emopt && python3.6 install.py 
ENV PETSC_DIR="/home/.emopt"
ENV SLEPC_DIR="/home/.emopt"
RUN pip3 install mpi4py==3.0.3 petsc4py==3.12.0 slepc4py==3.12.0 future --user
RUN cd /home/emopt/ && python3.6 setup.py install --user

ENV PYTHONPATH "/home/.local/lib/python3.6/site-packages:/home/.local/lib/python3.6/site-packages/emopt-2023.1.16-py3.6.egg"
